### ISSUE TITLE
Huge templates wrong file names

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#39]
Latest zip contains, for example, "elf" not "elven" templates.

**Comment by morvael** [comment]
Also "sauron_modifer"

**Comment by ketura** [comment]
D'oh!  These were due to typos in the master *.xcf file that I use for exporting everything, where the file names are taken from layer names.  These were all fixed long ago, but apparently only the generator-included files were updated.  The files were actually incorrect in all three zip sizes.

These have been fixed in all three zips.
