### ISSUE TITLE
Using full cards as portraits

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#7]
It would be great if full cards could be used as portraits. Their size should simply match full template size, and they should be drawn first, with template rendered on top. That way the "window" of the template should show portrait from the original card, without the need to cut it and resize.

**Comment by ketura** [comment]
I have added the full_portrait tag.  When included in the tags column, it will alter the behavior of character, modifier, or site portraits to fill the entire card background instead of the normal portrait area (sites are also autorotated 270 degrees as normal).  

This should work for most card images, but keep in mind that a lot of them are off by a pixel or so, and the jagged card portrait areas are likely to be problematic.
