### ISSUE TITLE
'Ring-bearer' keyword is not treated as a special one in game text

### ISSUE THREAD

**Issue by witko0** [ketura/LotR-TCG_card_generator#9]

**Comment by ketura** [comment]
This is done on purpose.  There are a handful of keywords which are not auto-bolded because it would be triggered at times when the keyword should not be bold.

Consider the following cards:

https://lotrtcgwiki.com/wiki/lotr03024
https://lotrtcgwiki.com/wiki/lotr01224

There are more instances of "Ring-bearer" being normal text than there are "Ring-bearer" in bold.

You will need to manually format this keyword.  Simply write the game text as `<b>Ring-bearer.</b>` on the appropriate card.
